# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6df25315b2896de68513d0288a4687d6f691837e923ff16c3ed22c50858d5da22585765eec72524dc77b92d9dcc57e8db730141a0475e7b8edfbc2f7858e866

test:
  secret_key_base: 0c8e68dd23e23206525f8f6119a45fe9632071a5f8863313e2a1dc7dc2d397e6564728ba21679f91e3a2036157b440c22b2113d8f00a28f756fc94da949e15d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
